//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatkhlislamov_Autoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public string м { get; set; }
        public string мужской { get; set; }
        public string ж { get; set; }
        public string жескний { get; set; }
    }
}
